-- =====================================================================
-- KENDO - IMPORT LEAD CAMPAGNE (da CSV Marketing FIT Padova 2026-05-22)
-- =====================================================================
-- Esegui DOPO supabase_setup.sql.
-- Inserisce 161 lead campagne nella tabella `leads` con stato 'nuovo'.
-- =====================================================================

BEGIN;

INSERT INTO leads (nome, cognome, email, telefono, fonte) VALUES ('Alessandra', 'Tomasin', 'ale.tomasin@gmail.com', '+393472991060', 'LEAD local');
INSERT INTO leads (nome, cognome, email, telefono, fonte) VALUES ('Alessandra', 'Badalamenti', 'alessandra.badal@gmail.com', '+393207093469', 'LEAD franchising');
INSERT INTO leads (nome, cognome, email, telefono, fonte) VALUES ('Alessia', 'Villazzi', 'alessia.villazzi@libero.it', '+393476407865', 'LEAD local');
INSERT INTO leads (nome, cognome, email, telefono, fonte) VALUES ('Alessia', 'Benzi', 'alessiabenzi10@gmail.com', '+393277526929', 'LEAD local');
INSERT INTO leads (nome, cognome, email, telefono, fonte) VALUES ('Alexandra', 'Elena', 'alexandraantoce@yahoo.com', '+393271779393', 'LEAD local');
INSERT INTO leads (nome, cognome, email, telefono, fonte) VALUES ('alice', 'poffo', 'alice.poffoschmid@gmail.com', '+393756237343', 'LEAD franchising');
INSERT INTO leads (nome, cognome, email, telefono, fonte) VALUES ('Annakatia', 'Di Matteo', 'annakatiadimatteo@hotmail.it', '+393401727903', 'LEAD local');
INSERT INTO leads (nome, cognome, email, telefono, fonte) VALUES ('Annalisa', 'Trenti', 'annalisa.trenti@gmail.com', '+393493752763', 'LEAD local');
INSERT INTO leads (nome, cognome, email, telefono, fonte) VALUES ('regina', 'Rubin', 'aurisa12996@gmail.com', '+393791344331', 'LEAD local');
INSERT INTO leads (nome, cognome, email, telefono, fonte) VALUES ('Ausilia', 'Elia', 'ausilia.elia77@gmail.com', '+393494360066', 'LEAD local');
INSERT INTO leads (nome, cognome, email, telefono, fonte) VALUES ('Ayoub', 'Venezia', 'ayoubtcno3@gmail.com', '+393892628127', 'LEAD local');
INSERT INTO leads (nome, cognome, email, telefono, fonte) VALUES ('Barbara', 'Amendola', 'barbara.amendola1@virgilio.it', '+393392015644', 'LEAD local');
INSERT INTO leads (nome, cognome, email, telefono, fonte) VALUES ('Barbara', 'Gaiani', 'barbi.1971@libero.it', '+393477668666', 'LEAD local');
INSERT INTO leads (nome, cognome, email, telefono, fonte) VALUES ('Benedetta', 'Lari', 'benny-ciank@hotmail.it', '+393920182006', 'LEAD local');
INSERT INTO leads (nome, cognome, email, telefono, fonte) VALUES ('Zoriana', 'Homchak', 'bestzoriana@hotmail.com', '+19056163212', 'LEAD local');
INSERT INTO leads (nome, cognome, email, telefono, fonte) VALUES ('Bruna', 'Franco', 'brunafranco452@gmail.com', '+393345490278', 'LEAD local');
INSERT INTO leads (nome, cognome, email, telefono, fonte) VALUES ('Campomilla', 'Valente', 'camivalente22@gmail.com', '+393442690196', 'LEAD local');
INSERT INTO leads (nome, cognome, email, telefono, fonte) VALUES ('Antonio', 'Antonio', 'capozioantonio@gmail.com', '+393667085674', 'LEAD local');
INSERT INTO leads (nome, cognome, email, telefono, fonte) VALUES ('Chiara', 'Vigato', 'chiaravigato@yahoo.it', '+393474916360', 'LEAD local');
INSERT INTO leads (nome, cognome, email, telefono, fonte) VALUES ('Veronica', 'Chitoroaga', 'chitoroaga.veronica18@mail.com', '+13205646896', 'LEAD local');
INSERT INTO leads (nome, cognome, email, telefono, fonte) VALUES ('Cinzia De', 'Biagi', 'cinziadbg62@gmail.com', '+393391614868', 'LEAD local');
INSERT INTO leads (nome, cognome, email, telefono, fonte) VALUES ('claudia', 'ceccato', 'clacecc181171@gmail.com', '+393479140999', 'LEAD local');
INSERT INTO leads (nome, cognome, email, telefono, fonte) VALUES ('Vanessa', 'Corda', 'cordavane@gmail.com', '+393409803822', 'LEAD sito');
INSERT INTO leads (nome, cognome, email, telefono, fonte) VALUES ('Mino', 'Greco', 'cosimo.greco@kering.com', '+393490521511', 'LEAD local');
INSERT INTO leads (nome, cognome, email, telefono, fonte) VALUES ('Cristina', 'Zanovello', 'cristina@dr-esteticamedica.it', '+3934660509109', 'LEAD local');
INSERT INTO leads (nome, cognome, email, telefono, fonte) VALUES ('Patty', 'Daniele', 'danielepatrizia2@gmail.com', '+393913504857', 'LEAD local');
INSERT INTO leads (nome, cognome, email, telefono, fonte) VALUES ('Deanna', 'Zubani', 'deanna.zubani@gmail.com', '+393394465355', 'LEAD local');
INSERT INTO leads (nome, cognome, email, telefono, fonte) VALUES ('Denise', 'Amato', 'denise.amato78@gmail.com', '+393296251013', 'LEAD local');
INSERT INTO leads (nome, cognome, email, telefono, fonte) VALUES ('Debora', 'Minotto', 'dminotto@icloud.com', '+393482330073', 'LEAD local');
INSERT INTO leads (nome, cognome, email, telefono, fonte) VALUES ('#iome', 'Rossini', 'dora@margas.it', '+393475555912', 'LEAD local');
INSERT INTO leads (nome, cognome, email, telefono, fonte) VALUES ('Eugenia', 'Caruso', 'ecaruso1981@gmail.com', '+393394485684', 'LEAD franchising');
INSERT INTO leads (nome, cognome, email, telefono, fonte) VALUES ('Edna', 'da Silva', 'edisilvi@hotmail.it', '+393204472544', 'LEAD local');
INSERT INTO leads (nome, cognome, email, telefono, fonte) VALUES ('Elena', 'Michelotto', 'elenamichelotto@gmail.com', '+393924495237', 'LEAD sito');
INSERT INTO leads (nome, cognome, email, telefono, fonte) VALUES ('Federica', 'Pittarello', 'f.pittarello2012@gmail.com', '+393517378077', 'LEAD local');
INSERT INTO leads (nome, cognome, email, telefono, fonte) VALUES ('federica', 'B', 'federica70-f@libero.it', '+393935801275', 'LEAD local');
INSERT INTO leads (nome, cognome, email, telefono, fonte) VALUES ('Annamaria', 'Giurisato', 'felicissimoduetto@gmail.com', '+393505884062', 'LEAD franchising');
INSERT INTO leads (nome, cognome, email, telefono, fonte) VALUES ('Alessia', 'Ferro', 'ferroalessia121@gmail.com', '+393801838088', 'LEAD local');
INSERT INTO leads (nome, cognome, email, telefono, fonte) VALUES ('Filippo', 'Biasiotto', 'filippobiasiotto@gmail.com', '+393474918664', 'LEAD local');
INSERT INTO leads (nome, cognome, email, telefono, fonte) VALUES ('Flavio', 'Cataletto', 'flaviocataletto@hotmail.com', '+393313956408', 'LEAD local');
INSERT INTO leads (nome, cognome, email, telefono, fonte) VALUES ('Domaneant Florinela', 'Denisa', 'florentina.denisa96@gmail.com', '+393921164167', 'LEAD local');
INSERT INTO leads (nome, cognome, email, telefono, fonte) VALUES ('Francesca', 'Rampinelli', 'francescarampinelli@hotmail.it', '+393275848301', 'LEAD local');
INSERT INTO leads (nome, cognome, email, telefono, fonte) VALUES ('Francesca', 'Saba', 'francescasaba@email.it', '+393490859663', 'LEAD local');
INSERT INTO leads (nome, cognome, email, telefono, fonte) VALUES ('Francesco', 'Rizzi', 'francesco.rizzi88@gmail.com', '+393492184866', 'LEAD local');
INSERT INTO leads (nome, cognome, email, telefono, fonte) VALUES ('Antonella', 'Giacon', 'fulvio.fuschi@elmospa.com', '+393483384410', 'LEAD local');
INSERT INTO leads (nome, cognome, email, telefono, fonte) VALUES ('Festa Totale', 'Festa Totale', 'gi@gmail.xom', '+393457654129', 'LEAD local');
INSERT INTO leads (nome, cognome, email, telefono, fonte) VALUES ('Gianna', 'Par', 'giannaparo@yahoo.it', '+393335755345', 'LEAD local');
INSERT INTO leads (nome, cognome, email, telefono, fonte) VALUES ('Giulia', 'Bortolozzo', 'giulia.bortolozzo89@gmail.com', '+393928375360', 'LEAD local');
INSERT INTO leads (nome, cognome, email, telefono, fonte) VALUES ('Giacomo', 'Giuliani', 'giuliani.giacomo3@gmail.com', '+393337600518', 'LEAD local');
INSERT INTO leads (nome, cognome, email, telefono, fonte) VALUES ('Giulia', 'Martignon', 'giulymartignon@gmail.com', '+393477462521', 'LEAD local');
INSERT INTO leads (nome, cognome, email, telefono, fonte) VALUES ('Giuseppe', 'Consiglio', 'giuseppeconsi@gmail.com', '+393667546093', 'LEAD local');
INSERT INTO leads (nome, cognome, email, telefono, fonte) VALUES ('Giusy', 'Volo', 'giusy.volo@gmail.com', '+3289080094', 'LEAD local');
INSERT INTO leads (nome, cognome, email, telefono, fonte) VALUES ('Gualtiero', 'Alvisi', 'gualtax@gmail.com', '+393282161733', 'LEAD sito');
INSERT INTO leads (nome, cognome, email, telefono, fonte) VALUES ('Marian Hassan', 'Ali', 'hassanalimarian@hotmail.it', '+393497029412', 'LEAD local');
INSERT INTO leads (nome, cognome, email, telefono, fonte) VALUES ('Ines Henia.?????', 'Henia', 'heniaines@gmail.com', '+393497898718', 'LEAD local');
INSERT INTO leads (nome, cognome, email, telefono, fonte) VALUES ('Elena Di', 'Lapi', 'infohair80@gmail.com', '+393403281174', 'LEAD local');
INSERT INTO leads (nome, cognome, email, telefono, fonte) VALUES ('Mariana', 'Rispoli', 'informazione.aria@gmail.com', '+393495314048', 'LEAD local');
INSERT INTO leads (nome, cognome, email, telefono, fonte) VALUES ('Amila', 'Sudarshi', 'jeevenfernando@gmail.com', '+94774360356', 'LEAD local');
INSERT INTO leads (nome, cognome, email, telefono, fonte) VALUES ('Jessica', 'D''Errico', 'jessiderrico@hotmail.com', '+393401009234', 'LEAD local');
INSERT INTO leads (nome, cognome, email, telefono, fonte) VALUES ('Katia', 'Vucic', 'katiavucic@hotmail.com', '+393801876194', 'LEAD local');
INSERT INTO leads (nome, cognome, email, telefono, fonte) VALUES ('Chiara', 'Facchinello', 'kiarafacchi1989@gmail.com', '+393483931298', 'LEAD local');
INSERT INTO leads (nome, cognome, email, telefono, fonte) VALUES ('Anna', 'Kotni', 'kotnihanane@gmail.com', '+393803839609', 'LEAD local');
INSERT INTO leads (nome, cognome, email, telefono, fonte) VALUES ('Mary', 'Lai', 'laimarina4@gmail.com', '+393478143677', 'LEAD local');
INSERT INTO leads (nome, cognome, email, telefono, fonte) VALUES ('Niku', 'Niku', 'landibreg20@gmail.com', '+393792409942', 'LEAD local');
INSERT INTO leads (nome, cognome, email, telefono, fonte) VALUES ('Laura', 'Messori', 'lauramonmess@gmail.com', '+393480068943', 'LEAD local');
INSERT INTO leads (nome, cognome, email, telefono, fonte) VALUES ('Laura', 'Pittis', 'laurapittis@hotmail.com', '+393343438686', 'LEAD local');
INSERT INTO leads (nome, cognome, email, telefono, fonte) VALUES ('Daniela', 'Lionello', 'lionellodaniela@gmail.com', '+393358359696', 'LEAD local');
INSERT INTO leads (nome, cognome, email, telefono, fonte) VALUES ('Lorenza Scanavin', 'Scanavin', 'lory.scanavin@gmail.com', '+393472948522', 'LEAD franchising');
INSERT INTO leads (nome, cognome, email, telefono, fonte) VALUES ('Wearewine Italianmood', 'Bvi', 'luca.boaretto81@gmail.com', '+393807564970', 'LEAD local');
INSERT INTO leads (nome, cognome, email, telefono, fonte) VALUES ('Lucia', 'Biziato', 'luciaabiziato@gmail.com', '+393498702166', 'LEAD local');
INSERT INTO leads (nome, cognome, email, telefono, fonte) VALUES ('Lucrezia Lula', 'Nerviani', 'lucrezia.nerviani@gmail.com', '+393471886353', 'LEAD local');
INSERT INTO leads (nome, cognome, email, telefono, fonte) VALUES ('Martina', 'Breveglieri', 'm.breveglieri93@gmail.com', '+393402824392', 'LEAD local');
INSERT INTO leads (nome, cognome, email, telefono, fonte) VALUES ('Maddalena', 'Tizianel', 'maddalena.tizianel@hotmail.com', '+393497915396', 'LEAD local');
INSERT INTO leads (nome, cognome, email, telefono, fonte) VALUES ('Margherita', 'Chizzolini', 'margherita.chizzolini@gmail.com', '+393452241901', 'LEAD sito');
INSERT INTO leads (nome, cognome, email, telefono, fonte) VALUES ('marimich', 'Michelini', 'mari.mich.mm@gmail.com', '+393403081276', 'LEAD local');
INSERT INTO leads (nome, cognome, email, telefono, fonte) VALUES ('Marianna', 'Milan', 'marianna.milan@libero.it', '+393455782819', 'LEAD local');
INSERT INTO leads (nome, cognome, email, telefono, fonte) VALUES ('Marica', 'Ammoscato', 'maricammoscato@gmail.com', '+393891777000', 'LEAD local');
INSERT INTO leads (nome, cognome, email, telefono, fonte) VALUES ('Martina', 'Versuraro', 'martina.vers@gmail.com', '+393475141114', 'LEAD local');
INSERT INTO leads (nome, cognome, email, telefono, fonte) VALUES ('Michela', 'Quadrelli Peninetti', 'michelaquadrellipeninetti@gmail.comm', '+393283514723', 'LEAD local');
INSERT INTO leads (nome, cognome, email, telefono, fonte) VALUES ('Michele', 'Bordin', 'michelebordin.bordin@gmail.com', '+393926957849', 'LEAD local');
INSERT INTO leads (nome, cognome, email, telefono, fonte) VALUES ('mimmo', 'Positano', 'mimmoposi@gmail.com', '+393891140980', 'LEAD local');
INSERT INTO leads (nome, cognome, email, telefono, fonte) VALUES ('Mirko', 'Poletto', 'mirkobest07@hotmail.it', '+393386668949', 'LEAD local');
INSERT INTO leads (nome, cognome, email, telefono, fonte) VALUES ('Marialaura', 'Pintonello', 'mlaura.pintonello@alice.it', '+393485137248', 'LEAD local');
INSERT INTO leads (nome, cognome, email, telefono, fonte) VALUES ('Aylin', 'molaei', 'molaeiaylin@gmail.com', '+393463799364', 'LEAD sito');
INSERT INTO leads (nome, cognome, email, telefono, fonte) VALUES ('Monica', 'Frasson', 'monica.frasson@zf.com', '+393284528780', 'LEAD local');
INSERT INTO leads (nome, cognome, email, telefono, fonte) VALUES ('Monica', 'Rampazzo', 'monica.rampazzo50@gmail.com', '+393497791356', 'LEAD local');
INSERT INTO leads (nome, cognome, email, telefono, fonte) VALUES ('Monica', 'Marchesan', 'monicamarchesan35@gmail.com', '+393481500040', 'LEAD local');
INSERT INTO leads (nome, cognome, email, telefono, fonte) VALUES ('Greta', 'Noventa', 'n.greta@live.it', '+393409367217', 'LEAD local');
INSERT INTO leads (nome, cognome, email, telefono, fonte) VALUES ('Melania', 'Napolitano', 'napolitano.melania@gmail.com', '+393489199363', 'LEAD local');
INSERT INTO leads (nome, cognome, email, telefono, fonte) VALUES ('Serena', 'Sesana', 'nena.sesana@libero.it', '+393280263677', 'LEAD local');
INSERT INTO leads (nome, cognome, email, telefono, fonte) VALUES ('Rik', 'Nexus', 'nexuswave@gmail.com', '+393486111620', 'LEAD local');
INSERT INTO leads (nome, cognome, email, telefono, fonte) VALUES ('Nicoletta', 'Sireci', 'nicolettasireci@gmail.it', '+3663769683', 'LEAD local');
INSERT INTO leads (nome, cognome, email, telefono, fonte) VALUES ('rira', 'za', 'nixy1977a@gmail.com', '+393402221844', 'LEAD franchising');
INSERT INTO leads (nome, cognome, email, telefono, fonte) VALUES ('Arnaut', 'Olga', 'olga_arnaut@rocketmail.com', '+393807680000', 'LEAD local');
INSERT INTO leads (nome, cognome, email, telefono, fonte) VALUES ('GIADA', 'PETRANZAN', 'padaig17@gmail.com', '+39347485262', 'LEAD sito');
INSERT INTO leads (nome, cognome, email, telefono, fonte) VALUES ('Paola', 'Petrin', 'paola.petrin@gmail.com', '+393496667274', 'LEAD local');
INSERT INTO leads (nome, cognome, email, telefono, fonte) VALUES ('Paola', 'Ronchi', 'paolaronchi47@gmail.com', '+393407908062', 'LEAD local');
INSERT INTO leads (nome, cognome, email, telefono, fonte) VALUES ('Gloria', 'Patricia', 'patsyguti12@hotmail.com', '+393497936514', 'LEAD local');
INSERT INTO leads (nome, cognome, email, telefono, fonte) VALUES ('Silvana | Makeup Artist', 'pro', 'peruzzi.silvana@gmail.com', '+393393365838', 'LEAD local');
INSERT INTO leads (nome, cognome, email, telefono, fonte) VALUES ('PierAndrea Squarcina', 'Squarcina PierAndrea', 'pierandrea.squarcina@alice.it', '+393388869090', 'LEAD franchising');
INSERT INTO leads (nome, cognome, email, telefono, fonte) VALUES ('Gigliola', 'Berlose', 'piergilly@gmail.com', '+393400996590', 'LEAD franchising');
INSERT INTO leads (nome, cognome, email, telefono, fonte) VALUES ('Pietro', 'Morrone', 'pietromorrone1967@libero.it', '+393519525364', 'LEAD local');
INSERT INTO leads (nome, cognome, email, telefono, fonte) VALUES ('Rita', 'Curatolo', 'ri.chratolo@outlook.com', '+393921546888', 'LEAD franchising');
INSERT INTO leads (nome, cognome, email, telefono, fonte) VALUES ('Niwhara Reis', 'Freitas', 'rniwhara@gmail.com', '+393806404514', 'LEAD local');
INSERT INTO leads (nome, cognome, email, telefono, fonte) VALUES ('R.T.', 'Tognon', 'rominatognon@gmail.com', '+393355933924', 'LEAD local');
INSERT INTO leads (nome, cognome, email, telefono, fonte) VALUES ('Rosalia', 'Volebole', 'rosalia.volebole@gmail.com', '+13343154479', 'LEAD local');
INSERT INTO leads (nome, cognome, email, telefono, fonte) VALUES ('Sabrina', 'Rumo', 'sabrinarumo1975@gmail.com', '+393486010631', 'LEAD local');
INSERT INTO leads (nome, cognome, email, telefono, fonte) VALUES ('Sara', 'Bellin', 'sarabellin88@gmail.com', '+393409212440', 'LEAD local');
INSERT INTO leads (nome, cognome, email, telefono, fonte) VALUES ('Silvia', 'Michelon', 'silvialuca4@libero.it', '+393497945389', 'LEAD local');
INSERT INTO leads (nome, cognome, email, telefono, fonte) VALUES ('Simona', 'Sida', 'simonasida8@gmail.com', '+393515429623', 'LEAD local');
INSERT INTO leads (nome, cognome, email, telefono, fonte) VALUES ('Stefania', 'Munegato', 'stefaniamunegato@libero.it', '+393286975628', 'LEAD local');
INSERT INTO leads (nome, cognome, email, telefono, fonte) VALUES ('Gianluca', 'Tedesco', 'tedescogianluca2@gmail.com', '+393356473277', 'LEAD franchising');
INSERT INTO leads (nome, cognome, email, telefono, fonte) VALUES ('Tomas', 'Cavaliere', 'tomascavaliere@libero.it', '+393450810476', 'LEAD local');
INSERT INTO leads (nome, cognome, email, telefono, fonte) VALUES ('Rita', 'Dudas', 'topziarita@gmail.com', '+393668976648', 'LEAD local');
INSERT INTO leads (nome, cognome, email, telefono, fonte) VALUES ('Patricia', 'Torres', 'torrespatricia2504@icloud.com', '+393336147022', 'LEAD local');
INSERT INTO leads (nome, cognome, email, telefono, fonte) VALUES ('Caterina', 'Ursida', 'ursidacaterina@gmail.com', '+393792909211', 'LEAD franchising');
INSERT INTO leads (nome, cognome, email, telefono, fonte) VALUES ('Gaia', 'Valente', 'valentegaia@yahoo.it', '+393462166961', 'LEAD local');
INSERT INTO leads (nome, cognome, email, telefono, fonte) VALUES ('Valeriana', 'Lovato', 'valeriana.lov@gmail.com', '+393477954805', 'LEAD local');
INSERT INTO leads (nome, cognome, email, telefono, fonte) VALUES ('Ilaria', 'Valletta', 'vallettailaria@libero.it', '+393803797377', 'LEAD local');
INSERT INTO leads (nome, cognome, email, telefono, fonte) VALUES ('Vania', 'Moscardin', 'vaniamoscardin86@gmail.com', '+393293461644', 'LEAD local');
INSERT INTO leads (nome, cognome, email, telefono, fonte) VALUES ('vera', 'Bogdan', 'verabogdan93@gmail.com', '+393209592313', 'LEAD local');
INSERT INTO leads (nome, cognome, email, telefono, fonte) VALUES ('Veronica', 'Gazzetta', 'veroverog@hotmail.it', '+393479710935', 'LEAD local');
INSERT INTO leads (nome, cognome, email, telefono, fonte) VALUES ('vish', 'perera', 'vishperera665@gmail.com', '+393755853272', 'LEAD local');
INSERT INTO leads (nome, cognome, email, telefono, fonte) VALUES ('patrizia', 'visona', 'visona.patrizia@gmail.com', '+393385910000', 'LEAD franchising');
INSERT INTO leads (nome, cognome, email, telefono, fonte) VALUES ('Stefania', 'Lerose', 'xdiddlx@yahoo.it', '+393479661312', 'LEAD local');
INSERT INTO leads (nome, cognome, email, telefono, fonte) VALUES ('Alessia', 'Facco', '***', NULL, 'LEAD local');
INSERT INTO leads (nome, cognome, email, telefono, fonte) VALUES ('love me', 'Alexandra', '***', NULL, 'LEAD local');
INSERT INTO leads (nome, cognome, email, telefono, fonte) VALUES ('Archivio Tano', 'Festa', '***', NULL, 'LEAD local');
INSERT INTO leads (nome, cognome, email, telefono, fonte) VALUES ('Anna Chiara', 'Monte', '***', NULL, 'LEAD franchising');
INSERT INTO leads (nome, cognome, email, telefono, fonte) VALUES ('Marsida', 'Ustabeqiri', '***', NULL, 'LEAD local');
INSERT INTO leads (nome, cognome, email, telefono, fonte) VALUES ('Antonella', 'Astolfi', '***', NULL, 'LEAD franchising');
INSERT INTO leads (nome, cognome, email, telefono, fonte) VALUES ('Bardhe', 'Kovaci', '***', NULL, 'LEAD local');
INSERT INTO leads (nome, cognome, email, telefono, fonte) VALUES ('Bettina', 'Minaldo', '***', NULL, 'LEAD local');
INSERT INTO leads (nome, cognome, email, telefono, fonte) VALUES ('Consuelo', 'Giantin', '***', NULL, 'LEAD local');
INSERT INTO leads (nome, cognome, email, telefono, fonte) VALUES ('Daniela', 'Mustara', '***', NULL, 'LEAD local');
INSERT INTO leads (nome, cognome, email, telefono, fonte) VALUES ('Elena', 'Stella', '***', NULL, 'LEAD local');
INSERT INTO leads (nome, cognome, email, telefono, fonte) VALUES ('Elisabetta', 'Moro', '***', NULL, 'LEAD local');
INSERT INTO leads (nome, cognome, email, telefono, fonte) VALUES ('Roberta', 'righetti', '***', NULL, 'LEAD local');
INSERT INTO leads (nome, cognome, email, telefono, fonte) VALUES ('Ewa', 'Dygas', '***', NULL, 'LEAD local');
INSERT INTO leads (nome, cognome, email, telefono, fonte) VALUES ('Paolo', 'falferi', '***', NULL, 'LEAD local');
INSERT INTO leads (nome, cognome, email, telefono, fonte) VALUES ('Stefano', 'Benetti', '***', NULL, 'LEAD local');
INSERT INTO leads (nome, cognome, email, telefono, fonte) VALUES ('Giuseppe', 'Callegaro', '***', NULL, 'LEAD local');
INSERT INTO leads (nome, cognome, email, telefono, fonte) VALUES ('silvia', 'Galante', '***', NULL, 'LEAD local');
INSERT INTO leads (nome, cognome, email, telefono, fonte) VALUES ('Daniela', 'vede', '***', NULL, 'LEAD local');
INSERT INTO leads (nome, cognome, email, telefono, fonte) VALUES ('Isabel', 'Infante', '***', NULL, 'LEAD local');
INSERT INTO leads (nome, cognome, email, telefono, fonte) VALUES ('_ ??????????????????????_', 'Laimer', '***', NULL, 'LEAD local');
INSERT INTO leads (nome, cognome, email, telefono, fonte) VALUES ('Loredana', 'Rossetto', '***', NULL, 'LEAD local');
INSERT INTO leads (nome, cognome, email, telefono, fonte) VALUES ('Marilena', 'Marchiori', '***', NULL, 'LEAD local');
INSERT INTO leads (nome, cognome, email, telefono, fonte) VALUES ('Martina', 'Di Donato', '***', NULL, 'LEAD local');
INSERT INTO leads (nome, cognome, email, telefono, fonte) VALUES ('Michela', 'Cardin', '***', NULL, 'LEAD local');
INSERT INTO leads (nome, cognome, email, telefono, fonte) VALUES ('Mina', 'Cheema', '***', NULL, 'LEAD local');
INSERT INTO leads (nome, cognome, email, telefono, fonte) VALUES ('Moira', 'Benvegnu', '***', NULL, 'LEAD local');
INSERT INTO leads (nome, cognome, email, telefono, fonte) VALUES ('Paulina', 'Puchi', '***', NULL, 'LEAD local');
INSERT INTO leads (nome, cognome, email, telefono, fonte) VALUES ('Sabah', 'VD', '***', NULL, 'LEAD local');
INSERT INTO leads (nome, cognome, email, telefono, fonte) VALUES ('Simona', 'Simo', '***', NULL, 'LEAD local');
INSERT INTO leads (nome, cognome, email, telefono, fonte) VALUES ('Stefania', 'Franzina', '***', NULL, 'LEAD local');
INSERT INTO leads (nome, cognome, email, telefono, fonte) VALUES ('Elena', 'Sturaro', '***', NULL, 'LEAD local');
INSERT INTO leads (nome, cognome, email, telefono, fonte) VALUES ('Artila', 'Krasniqi', '***', NULL, 'LEAD local');
INSERT INTO leads (nome, cognome, email, telefono, fonte) VALUES ('Valentina', 'Tonello', '***', NULL, 'LEAD local');
INSERT INTO leads (nome, cognome, email, telefono, fonte) VALUES ('Valentina', 'Tabac', '***', NULL, 'LEAD local');
INSERT INTO leads (nome, cognome, email, telefono, fonte) VALUES ('Alessandro', 'Villa', '***', NULL, 'LEAD local');
INSERT INTO leads (nome, cognome, email, telefono, fonte) VALUES ('Zinaida', 'Tomsa', '***', NULL, 'LEAD local');
COMMIT;
